# Get the wpctl music id:
# 1. Get client ID from pactl list clients (paragraph mode → find spotify → extract Client #82 → 82)
# 2. Get sink-input & node ID from pactl list sink-inputs (find Client: 82 → extract Sink Input #83 and object.id = "77")
# $CLIENT_ID=$(pactl list clients | awk -v RS= '/application\.name = "spotify"/ {gsub("#","",$2); print $2; exit}')
$SINK_INPUT_ID=$(wpctl status | awk '/Streams:/{s=1} s && /audio-src/{print $1; exit}')
$musicSink = $SINK_INPUT_ID
$setMusicVolume = wpctl set-volume $musicSink
# $setMusicVolume = pactl set-sink-input-volume $musicSink
$getMusicVolume = wpctl get-volume $musicSink


bindle = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 0.02+
bindle = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02-

# bindle = CTRL, XF86AudioRaiseVolume, exec, playerctl --player=spotify volume 0.05+
# bindle = CTRL, XF86AudioLowerVolume, exec, playerctl --player=spotify volume 0.05-
bindle = CTRL, XF86AudioRaiseVolume, exec, $setMusicVolume 5%+
bindle = CTRL, XF86AudioLowerVolume, exec, $setMusicVolume 5%-

bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindlr = , XF86AudioPlay, exec, playerctl --player=spotify play-pause
bindlr = , XF86AudioStop, exec, playerctl --player=spotify play-pause

# bindlr = CTRL, XF86AudioStop, exec, playerctl --player=spotify play-pause

bindlr = CTRL SHIFT, XF86AudioRaiseVolume, exec, playerctl --player=spotify next
bindlr = CTRL SHIFT, XF86AudioLowerVolume, exec, playerctl --player=spotify previous

bindle = CTRL, XF86AudioPlay, exec, playerctl --player=spotify position 5-
bindle = CTRL, XF86AudioMute, exec, playerctl --player=spotify position 5+


# bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
# bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
# bindle = , XF86HomePage, exec, playerctl --player=spotify volume 0.05-
# bindle = , XF86Mail, exec, playerctl --player=spotify volume 0.05+
# bindle = CTRL, XF86HomePage, exec, playerctl --player=spotify volume 0.1-
# bindle = CTRL, XF86Mail, exec, playerctl --player=spotify volume 0.1+
# bindle = SHIFT, XF86HomePage, exec, playerctl --player=spotify volume 0.2-
# bindle = SHIFT, XF86Mail, exec, playerctl --player=spotify volume 0.2+

