windowrule {
	name = ulauncher
	match:class = ulauncher

	opacity = 0.9
	stay_focused = on
	# allows_input = on
	# focus_on_activate = on
	# idle_inhibit = alway
	# render_unfocused = on
	border_size = 0
}
exec-once = ulauncher

windowrule {
	name = browser
	match:class = zen
	workspace = 4
}
exec-once = zen-browser

windowrule {
	name = discord
	match:class = vesktop
	workspace = 5
}
exec-once = vesktop

windowrule {
	name = spotify
	match:class = Spotify
	workspace = 6
}
exec-once = spotify-launcher
