$monprime = DP-1
$monsecond = DVI-I-1

workspace = 1, monitor:$monprime
workspace = 2, monitor:$monprime
workspace = 3, monitor:$monprime
workspace = 4, monitor:$monsecond
workspace = 5, monitor:$monsecond
workspace = 6, monitor:$monsecond
workspace = 7, monitor:$monsecond
workspace = 8, monitor:$monsecond
workspace = 9, monitor:$monsecond
