bindl = , XF86AudioNext, exec, playerctl --player=spotify next
bindl = , XF86AudioPrev, exec, playerctl --player=spotify previous

bindle = , XF86AudioRewind, exec, playerctl --player=spotify position 5-
bindle = , XF86AudioForward, exec, playerctl --player=spotify position 5+
