$mainMod = SUPER
$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun

bind = $mainMod, M, workspace, 1
bind = $mainMod, comma, workspace, 2
bind = $mainMod, period, workspace, 3
bind = $mainMod, J, workspace, 4
bind = $mainMod, K, workspace, 5
bind = $mainMod, L, workspace, 6
bind = $mainMod, U, workspace, 7
bind = $mainMod, I, workspace, 8
bind = $mainMod, O, workspace, 9
bind = $mainMod, bracketleft, workspace, 10

bind = $mainMod CTRL, M, movetoworkspace, 1
bind = $mainMod CTRL, comma, movetoworkspace, 2
bind = $mainMod CTRL, period, movetoworkspace, 3
bind = $mainMod CTRL, J, movetoworkspace, 4
bind = $mainMod CTRL, K, movetoworkspace, 5
bind = $mainMod CTRL, L, movetoworkspace, 6
bind = $mainMod CTRL, U, movetoworkspace, 7
bind = $mainMod CTRL, I, movetoworkspace, 8
bind = $mainMod CTRL, O, movetoworkspace, 9
bind = $mainMod CTRL, bracketleft, movetoworkspace, 10
